server:
  port: 7073
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    rest:
      base-path: /api3
  boot:
   admin:
     client:
       url: http://localhost:1111/
  mail:
   host: smtp.gmail.com
   port: 587
   username: 
   password: 
   properties:
     mail:
      smtp:
        auth: true
        starttls:
        enable: true     
management:
  endpoints:
    web:
      exposure:
        include: '*'